### ISSUE TITLE
onBlur event

### ISSUE THREAD

**Issue by rykanohi1** [rykanohi1/Laptop-projects#11]
@joe-crick I've noticed that when I try to click on one of the contact list items the onBlur event fires on on the input and the contact list disappeared. I've tried to fix this by wrapping the input and contact list in a div and moving the onBlur event there, I have also replaced the div with a span, putting the onBlur event directly into the contact list component. It seems that the onBlur attribute might not work with divs, unless there's something I'm missing.

**Comment by joe-crick** [comment]
@rykanohi1 For more information on the `blur` event, you can see these:

* https://jsbin.com/qesolotimu/edit?html,output
* https://www.w3schools.com/jsref/event_onblur.asp - go to the Technical Details section.

React is kind of strange, in that its event model is a bit different from the DOM's. It's important to know this. React will bubble events that the DOM normally will not. If you don't know what bubbling events means, read this: https://javascript.info/bubbling-and-capturing.

If you call your toggle function from `onBlur`, then it's going to fire every time that your cursor leaves the input. This would mean that the user will never be able to click on the `Contact List`. So... Here's how I would deal with this for now. It's a little clunky, but it works.

```js

  constructor(props) {
    super(props);
    this.state = {
      searchTerm: '',
      contacts: props.contacts || [],
      isVisible: false
    };
    this.updateSearch = this.updateSearch.bind(this);
    // --> Break out your toggle into separate show and hide functions
    this.showContacts = this.showContacts.bind(this);
    this.hideContacts = this.hideContacts.bind(this);
    // --> Add the hide function as an event on the document. This way, it will fire whenever the user
    // clicks on the document.
    document.addEventListener('click', this.hideContacts);
  };


  showContacts() {
    this.setState(() => ({ isVisible: true }));
  };

  hideContacts() {
    this.setState(() => ({isVisible: false}))
  }

 {/* Attach the showContacts method to the onFocus event of the input */}
 <input
    className="search-filter"
    type="search"
    placeholder="search contacts"
    value={this.state.searchTerm}
    onChange={this.updateSearch}
    onFocus={this.showContacts}
  />

```
There is a more elegant, and more complex solution that gives you more flexibility. You can add a `div` to your page that expands to fill the visible area of the page, and sits a layer beneath the dropdown, but above all the other page content. This `div` is clickable and, when clicked, will close the dropdown. However, all clicks within the dropdown area will be fired within it, and can be utilized programmatically. If you want an idea of what this looks like, and how you'd implement it, I'll put something together.

**Comment by rykanohi1** [comment]
@joe-crick creating an event listener in the document made it so that whenever I clicked anything the contact list would disappear, including the initial click on the input, so clicking the input would briefly show the contact list and then it would disappear. I changed the document's event listener to a blur event rather than a click, and it seems to work, but something seems off about it.

**Comment by joe-crick** [comment]
@rykanohi1 Interesting. That worked for me---it's actually a fairly standard way to handle this circumstance. Will you check your changes in? I'll see what I can do with it.

**Comment by joe-crick** [comment]
@rykanohi1 Check in your changes yet?

**Comment by rykanohi1** [comment]
@joe-crick ya

**Comment by joe-crick** [comment]
@rykanohi1 I made a PR for this.
