### ISSUE TITLE
Search-bar Test

### ISSUE THREAD

**Issue by rykanohi1** [rykanohi1/Laptop-projects#6]
@joe-crick  I'm having trouble getting my latest test for the search-bar component to work. It pertains to the updateSearch method being called when the input value changes in order to change the searchTerm, but the searchTerm only returns undefined. I've tried refactoring the code, like removing the value attribute and using the click event or input event rather than the change event, as well as adding a class name to use instead of event.target.value, but I'm getting no luck.

Here is the response i get when I run the test suite:
 Expected value to equal:
      "a"
    Received:
      undefined

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      at Object.<anonymous> (components/search-bar/search-bar.test.js:26:32)
          at Promise (<anonymous>)
          at <anonymous>

**Comment by joe-crick** [comment]
There were a few things, here, to update. I created a PR with the changes, so you can compare what I did with your original code. The link to the PR is at the bottom of this reply.

The key things I did were:

* Fix your input. It needs to have an `onChange` attribute, and a `value` attribute:
```js
<input
   className="search-filter"
   type="search"
   value={this.state.searchTerm}
   onChange={this.updateSearch}/>
``` 
* I moved the binding of `updateSearch` to the constructor. This wasn't necessary, but it's the more standard way of binding the functions--i.e., it conforms to the way the React docs tell you to do it.

* You need to get the value for the field from the `event` object that is passed in from the `onChange` event. The `event`'s `target` property contains the DOM element that fired the `event`. In this case, the `target` is an `input` DOM element. `input`'s have a `value` property that contains their value. You use this value to update your state:

```js
updateSearch(event) {
    this.setState({searchTerm: event.target.value});
 };
```
* Finally, there were two changes to the test file. `state` is a function, not a property off of the object `enzyme` returns. And, what you're testing is the `change` event of the input, so I simulated the `change` event:

```js
 app.find('.search-filter').simulate('change', {target: {value: 'a'}});
 const actual = app.state().searchTerm;
```

Here is the PR:
https://github.com/rykanohi1/Laptop-projects/pull/7/files

**Comment by rykanohi1** [comment]
@joe-crick  i'm having another issue with the tests on my searchbar component, when I run them I get the message "cannot read property 'filter' of undefined", I tried substituting the .filter() that I used with .map() but that just messes everything up.

**Comment by joe-crick** [comment]
@rykanohi1 You either need to pass in the `contacts` to your component, or provide a default value for the `contacts` property in the `state` of your component. If `contacts` is required, you should provide a contract in your constructor that throws an error (`throw new Error("Whatever Error Here")`) if no contacts are provided.

```js
  constructor(props) {
    super(props);
    this.state = {
      searchTerm: '',
      // Provides a default value for contacts
      contacts: props.contacts || []
    };
    this.updateSearch = this.updateSearch.bind(this);
  };
```

Or:
```js
  constructor(props) {
    super(props);
    // Provide some kind of assertion/contract.
    if (!props.contacts) {
      throw new Error("Valid contacts are required to instantiate search bar.");
    }
    this.state = {
      searchTerm: '',
      contacts: props.contacts
    };
    this.updateSearch = this.updateSearch.bind(this);
  };
```

Or:

```js
    // Provide the contacts to the component.
    const app = shallow(<SearchBar contacts={["my","array","here"}/>);
```

_NOTE_: On another matter, you can simplify, and make more delcarative (i.e., descriptive) the following:

```js
// Replace me with the code below
contact.username.toLowerCase().indexOf(this.state.searchTerm.toLowerCase()) !== -1;
```
By writing this instead:

```js
// Replacing "indexOf" with "includes". "Includes" is more descriptive of the operation being performed. 
contact.username.toLowerCase().includes(this.state.searchTerm.toLowerCase());
```
See [String.prototype.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) for more information.

**Comment by rykanohi1** [comment]
@joe-crick tests are working but I keep getting this message that says " Warning: Each child in an array or iterator should have a unique "key" prop.", i've tried adding a key attribute to the contact component that uses an item's id as the key, but it doesn't do anything

**Comment by joe-crick** [comment]
@rykanohi1. The issue is with the children you're passing in to the `LeftRightLayout` component. You're passing in an array. 

```js
children={() => [
          <ActionButton
            className="contact-profile"
            imgSrc={contact.imgSrc}
            title={contact.address}
            label={contact.username}
            action={() => alert("history unavailable")}
          />,
          <ActionButton
            className="contact-viewer"
            imgSrc="https://png.icons8.com/metro/1600/contacts.png"
            action={() => alert("profile unavailable")}
          />
        ]}
```
Whenever you pass React an array to render, the items in the array need keys. Alternatively, you could do this:
```js
children={() =>
            <div>
              <ActionButton
                className="contact-profile"
                imgSrc={contact.imgSrc}
                title={contact.address}
                label={contact.username}
                action={() => alert("history unavailable")}
              />
              <ActionButton
                className="contact-viewer"
                imgSrc="https://png.icons8.com/metro/1600/contacts.png"
                action={() => alert("profile unavailable")}
              />
            </div>
          }
```
_Of Note_: In React 16, you can use a `React.Fragement` instead of a `div` to wrap the Buttons you're passing in--depending on what you want to do. The Fragment renders the HTML without an enclosing tag. Using the `div` wraps the content in the `div`. In your project, you'd need to add support for `React.Fragment` before you could use it.

**Comment by rykanohi1** [comment]
@joe-crick  I wrapped the children in contact-list with a div like in your second example, but i'm still getting the same error of "Warning: Each child in an array or iterator should have a unique "key" prop.".

**Comment by joe-crick** [comment]
@rykanohi1 Did you _remove_ the array?

**Comment by rykanohi1** [comment]
@joe-crick  well I have now, but there's still the same error

**Comment by joe-crick** [comment]
@rykanohi1 Check it in, and I'll look over it.

**Comment by joe-crick** [comment]
@rykanohi1 You need to add `id` properties to the contacts you're passing in to the search bar component--like so:

```js
{imgSrc: 'http://www.personalbrandingblog.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png', 
username: 'Jonathan', 
address: 'Jonathan01@email.com',
id: 1}
```
Make sure each ID is unique. Then, update the `ContactList` component, as follows:

```js
  <div className={`contact-list ${className}`}>
    {contacts.map((contact, index) => (
      <LeftRightLayout
        className="contact"
        key={index} // <-- Add the key here
        children={() =>
```
Note `{contacts.map((contact, index) => (` in the code above. This is the bit that requires a `key` property in the immediate node that follows it. You're mapping over something, and creating a list of elements. React needs a way to efficiently manage that list of elements, and it uses the `key` attribute to do this.
