### ISSUE TITLE
Toggling the classname

### ISSUE THREAD

**Issue by rykanohi1** [rykanohi1/Laptop-projects#8]
@joe-crick  I'm trying to toggle the classname of my contact-list component inside of the searchbar component, but nothing I try seems to work. I have used a similar arguement to the classname toggler you used in the dropdown component. I then tried to wrap the contact-list component in a div, which I used the same arguement on. Finally I tried just setting the classname of the contact-list manually to see if I could even apply a class to it from within the searchbar component at all. None of those three ideas worked.

**Comment by joe-crick** [comment]
@rykanohi1 There are a couple of things you need to change here. 

1. Your SCSS should look more like this:

```css
.contact-list {
  &.hide {
    display: none
  }
  &.show {
    display: block
  }
}
```
Read up on what the `&` operator does in SCSS: [Sass Ampersand](https://css-tricks.com/the-sass-ampersand/)

2. The way your CSS is structured, you need to have _two_ classes on the `div` element wrapping `ContactsList`. One easy way to do this is with JS templating:

```js
<div className={`contact-list ${this.state.isVisible ? 'show' : 'hide'}`}>
```
In the end, what's important is that you have final HTML that looks something like this (assuming the component is in `show` mode):

```html
<div class="contact-list show">
```
The key point is that you have two classes: `contact-list` and your `show` or `hide` class (depending on the state of the component).
